id: cart_links_settings
label: Cart Links configuration settings
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration

source:
  plugin: variable
  source_module: uc_cart_links
  variables:
    - uc_cart_links_empty
    - uc_cart_links_invalid_page
    - uc_cart_links_restrictions
    - uc_cart_links_add_show
    - uc_cart_links_track
    - uc_cart_links_messages

process:
  add_show: uc_cart_links_add_show
  track: uc_cart_links_track
  empty: uc_cart_links_empty
  messages: uc_cart_links_messages
  restrictions: uc_cart_links_restrictions
  invalid_page: uc_cart_links_invalid_page

destination:
  plugin: config
  config_name: uc_cart_links.settings
