# Schema for the configuration files of the Store module.

uc_store.settings:
  type: config_object
  label: 'Store settings'
  mapping:
    name:
      type: string
      label: 'The store name'
    mail:
      type: email
      label: 'The store e-mail address'
    mail_include_name:
      type: boolean
      label: 'Whether to include the store name as part of the From: e-mail address'
    phone:
      type: string
      label: 'The store telephone number'
    fax:
      type: string
      label: 'The store fax number'
    help_page:
      type: uri
      label: ''
    address:
      type: mapping
      label: 'The store mailing address'
      mapping:
        first_name:
          type: string
          label: 'The mailing address first name'
        last_name:
          type: string
          label: 'The mailing address last name'
        company:
          type: string
          label: 'The mailing address company'
        street1:
          type: string
          label: 'The mailing address street, line 1'
        street2:
          type: string
          label: 'The mailing address street, line 2'
        city:
          type: string
          label: 'The mailing address city'
        zone:
          type: string
          label: 'The mailing address zone'
        country:
          type: string
          label: 'The mailing address country'
        postal_code:
          type: string
          label: 'The mailing address postal code'
        phone:
          type: string
          label: 'Telephone number'
        email:
          type: email
          label: 'Email address'
    address_fields:
      type: mapping
      label: 'Fields to collect for customer addresses'
      mapping:
        first_name:
          type: mapping
          label: 'First name'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        last_name:
          type: mapping
          label: 'Last name'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        company:
          type: mapping
          label: 'Company'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        street1:
          type: mapping
          label: 'Street address, line 1'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        street2:
          type: mapping
          label: 'Street address, line 2'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        city:
          type: mapping
          label: 'City'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        zone:
          type: mapping
          label: 'State/Province/Zone'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        country:
          type: mapping
          label: 'Country'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        postal_code:
          type: mapping
          label: 'Postal code'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        phone:
          type: mapping
          label: 'Telephone number'
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
    currency:
      type: mapping
      label: 'Currency display settings'
      mapping:
        code:
          type: string
          label: '3-character currency code'
        symbol:
          type: string
          label: 'Currency symbol'
        symbol_after:
          type: boolean
          label: 'Currency symbol position'
        thousands_marker:
          type: string
          label: 'Currency thousands marker'
        decimal_marker:
          type: string
          label: 'Currency decimal marker'
        precision:
          type: integer
          label: 'Currency decimal places'
    weight:
      type: mapping
      label: 'Weight display settings'
      mapping:
        units:
          type: string
          label: 'Default weight units'
        thousands_marker:
          type: string
          label: 'Weight thousands marker'
        decimal_marker:
          type: string
          label: 'Weight decimal marker'
        precision:
          type: integer
          label: 'Weight decimal places'
    length:
      type: mapping
      label: 'Length display settings'
      mapping:
        units:
          type: string
          label: 'Default length units'
        thousands_marker:
          type: string
          label: 'Length thousands marker'
        decimal_marker:
          type: string
          label: 'Length decimal marker'
        precision:
          type: integer
          label: 'Length decimal places'
    customer_address:
      type: string
      label: 'Address type to use'
    capitalize_address:
      type: boolean
      label: 'Display address in all capital letters'
    footer_message:
      type: boolean
      label: 'Display footer message'

block.settings.powered_by_ubercart:
  type: block_settings
  label: 'Branding block'
  mapping:
    message:
      type: integer
      label: 'Message to use'
