id: attribute_settings
label: Product attribute configuration settings
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration

source:
  plugin: variable
  source_module: uc_attribute
  variables:
    - uc_attribute_option_price_format

process:
  option_price_format: uc_attribute_option_price_format

destination:
  plugin: config
  config_name: uc_attribute.settings
