id: d6_2checkout_settings
label: 2Checkout configuration settings
migration_tags:
  - Drupal 6
  - Configuration

source:
  plugin: variable
  source_module: uc_2checkout
  variables:
    - uc_2checkout_check
    - uc_2checkout_checkout_type
    - uc_2checkout_demo
    - uc_2checkout_language
    - uc_2checkout_secret_word
    - uc_2checkout_sid

process:
  check: uc_2checkout_check
  checkout_type: uc_2checkout_checkout_type
  demo: uc_2checkout_demo
  language: uc_2checkout_language
  secret_word: uc_2checkout_secret_word
  sid: uc_2checkout_sid

destination:
  plugin: config
  config_name: uc_2checkout.settings
