id: payment_pack_cod_settings
label: Payment Pack COD configuration settings
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration

source:
  plugin: variable
  source_module: uc_payment_pack
  variables:
    - uc_cod_policy
    - uc_cod_max_order
    - uc_cod_delivery_date

process:
  policy: uc_cod_policy
  max_order: uc_cod_max_order
  delivery_date: uc_cod_delivery_date

destination:
  plugin: config
  config_name: uc_payment_pack.cod.settings
