id: file_settings
label: File configuration settings
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration

source:
  plugin: variable
  source_module: uc_file
  variables:
    - uc_file_base_dir
    - uc_file_duplicate_warning
    - uc_file_download_limit_number
    - uc_file_download_limit_addresses
    - uc_file_download_limit_duration_qty
    - uc_file_download_limit_duration_granularity
    - uc_file_file_mask

process:
  base_dir: uc_file_base_dir
  download_limit_number: uc_file_download_limit_number
  download_limit_addresses: uc_file_download_limit_addresses
  download_limit_duration_qty: uc_file_download_limit_duration_qty
  download_limit_duration_granularity: uc_file_download_limit_duration_granularity
  duplicate_warning: uc_file_duplicate_warning
  file_mask: uc_file_file_mask

destination:
  plugin: config
  config_name: uc_file.settings
