uc_catalog.settings:
  type: config_object
  label: 'Product catalog settings'
  mapping:
    block_nodecount:
      type: boolean
      label: 'Display product counts?'
    block_title_link:
      type: boolean
      label: 'Make catalog block title a link to top-level catalog page?'
    breadcrumb:
      type: boolean
      label: 'Display catalog breadcrumb?'
    display:
      type: string
      label: 'Catalog View display to use'
    expand_categories:
      type: boolean
      label: 'Always expand categories?'
    vocabulary:
      type: string
      label: 'Vocabulary machine name'

block.settings.uc_catalog_block:
  type: block_settings
  label: 'Catalog block'
  mapping:
    link_title:
      type: boolean
      label: 'Make catalog block title a link to top-level catalog page?'
    expanded:
      type: boolean
      label: 'Always expand categories?'
    product_count:
      type: boolean
      label: 'Display product counts?'
