id: credit_settings
label: Credit configuration settings
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration

source:
  plugin: variable
  source_module: uc_credit
  variables:
    - uc_credit_encryption_path
    - uc_credit_validate_numbers
    - uc_credit_cvv_enabled
    - uc_credit_owner_enabled
    - uc_credit_start_enabled
    - uc_credit_issue_enabled
    - uc_credit_bank_enabled
    - uc_credit_type_enabled
    - uc_credit_accepted_types
    - uc_credit_visa
    - uc_credit_mastercard
    - uc_credit_discover
    - uc_credit_amex
    - uc_credit_policy
    - uc_credit_fail_message

process:
  validate_numbers: uc_credit_validate_numbers
  encryption_path: uc_credit_encryption_path
  cvv_enabled: uc_credit_cvv_enabled
  owner_enabled: uc_credit_owner_enabled
  start_enabled: uc_credit_start_enabled
  issue_enabled: uc_credit_issue_enabled
  bank_enabled: uc_credit_bank_enabled
  type_enabled: uc_credit_type_enabled
  accepted_types: uc_credit_accepted_types
  visa: uc_credit_visa
  mastercard: uc_credit_mastercard
  discover: uc_credit_discover
  amex: uc_credit_amex
  policy: uc_credit_policy
  fail_message: uc_credit_fail_message

destination:
  plugin: config
  config_name: uc_credit.settings
