# Schema for the configuration files of the Comment module.

uc_cart.messages:
  type: config_object
  label: 'Default cart messages'
  mapping:
    logged_in:
      type: text
      label: 'Logged-in user message'
    existing_user:
      type: text
      label: 'Existing user message'
    new_user:
      type: text
      label: 'New user message'
    new_user_logged_in:
      type: text
      label: 'New user logged-in message'
    langcode:
      type: string
      label: 'Language code'

uc_cart.settings:
  type: config_object
  label: 'Cart function settings'
  mapping:
    ajax:
      type: mapping
      label: 'Ajax flag'
      mapping:
        checkout:
          type: sequence
          label: 'Enable ajax on checkout page?'
          sequence:
            type: sequence
            label: 'Triggering form element'
            sequence:
              type: string
              label: 'Panes to update upon trigger'
    add_item_msg:
      type: boolean
      label: 'Display add item message'
    add_item_redirect:
      type: uri
      label: 'Redirect Uri for add-to-cart'
    msg_order_logged_in:
      type: text
      label: 'Message displayed upon checkout for a user who is logged in'
    msg_order_existing_user:
      type: text
      label: "Message displayed upon checkout for a user who has an account but wasn't logged in"
    msg_order_new_user:
      type: text
      label: 'Message displayed upon checkout for a new user whose account was just created'
    msg_order_new_user_logged_in:
      type: text
      label: 'Message displayed upon checkout for a new user whose account was just created and who is being logged in automatically'
    empty_button:
      type: boolean
      label: 'Display empty cart button'
    minimum_subtotal:
      type: integer
      label: 'Minimum order subtotal'
    anon_duration:
      type: integer
      label: 'Anonymous cart lifetime'
    anon_unit:
      type: string
      label: 'Anonymous cart lifetime units'
    auth_duration:
      type: integer
      label: 'Authenticated cart lifetime'
    auth_unit:
      type: string
      label: 'Authenticated cart lifetime units'
    continue_shopping_type:
      type: string
      label: 'Continue shopping form element type'
    continue_shopping_use_last_url:
      type: boolean
      label: 'Whether to return to last URL or not when continue shopping button is pushed'
    continue_shopping_url:
      type: uri
      label: 'If not continue_shopping_user_last_url, then return to this URL'
    breadcrumb_text:
      type: label
      label: "Custom breadcrumb text to use instead of 'Home'"
    breadcrumb_url:
      type: uri
      label: 'Cart page breadcrumb destination'
    new_customer_login:
      type: boolean
      label: 'Log in new customers after checkout'
    new_customer_email:
      type: boolean
      label: 'Send new customers a separate e-mail with their account details'
    new_customer_status_active:
      type: boolean
      label: 'Set new customer accounts to active'
    new_account_name:
      type: boolean
      label: 'Allow new customers to specify a username'
    new_account_password:
      type: boolean
      label: 'Allow new customers to specify a password'
    checkout_email_customer:
      type: boolean
      label: 'Send checkout email to customer'
    checkout_email_admin:
      type: boolean
      label: 'Send checkout email to administrator'
    mail_existing:
      type: boolean
      label: "Allow anonymous customers to use an existing account's email address"
    email_validation:
      type: boolean
      label: 'Require e-mail confirmation for anonymous customers'
    checkout_anonymous:
      type: boolean
      label: 'Enable anonymous checkout'
    checkout_enabled:
      type: boolean
      label: 'Enable checkout'
    panes:
      type: sequence
      label: 'Pane settings'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'Plugin ID'
          status:
            type: boolean
            label: 'Enabled status'
          weight:
            type: integer
            label: 'Ordinal'
          settings:
            type: uc_cart_pane.[%parent.id]

uc_cart_pane.billing:
  type: mapping
  label: 'Billing cart pane configuration settings'
  mapping:
    default_same_address:
      type: boolean
      label: 'Use the same address for billing and delivery by default'

uc_cart_pane.delivery:
  type: mapping
  label: 'Delivery cart pane configuration settings'
  mapping:
    delivery_not_shippable:
      type: boolean
      label: 'Hide delivery information when carts have no shippable items'

uc_cart_pane.cart:
  type: mapping
  label: 'Cart cart pane configuration settings'

uc_cart_pane.customer:
  type: mapping
  label: 'Customer cart pane configuration settings'

uc_cart_pane.comments:
  type: mapping
  label: 'Comments cart pane configuration settings'

action.configuration.uc_cart_add_product_action:
  type: action_configuration_default
  label: 'Cart add-to-cart configuration'

block.settings.uc_cart_block:
  type: block_settings
  label: 'Shopping cart block'
  mapping:
    hide_empty:
      type: boolean
      label: 'Hide block if cart is empty'
    show_image:
      type: boolean
      label: 'Display the shopping cart icon in the block title'
    collapsible:
      type: boolean
      label: 'Make the shopping cart block collapsible by clicking the name or arrow'
    collapsed:
      type: boolean
      label: 'Display the shopping cart block collapsed by default'
